// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: accounts_service.proto

#include "./message/accounts_service.pb.h"
#include "./grpc/accounts_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace accounts {

static const char* StudentService_method_names[] = {
  "/accounts.StudentService/CreateStudent",
  "/accounts.StudentService/GetStudent",
  "/accounts.StudentService/GetStudentByUserId",
  "/accounts.StudentService/UpdateStudent",
  "/accounts.StudentService/DeleteStudent",
  "/accounts.StudentService/ListStudents",
};

std::unique_ptr< StudentService::Stub> StudentService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StudentService::Stub> stub(new StudentService::Stub(channel, options));
  return stub;
}

StudentService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateStudent_(StudentService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStudent_(StudentService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStudentByUserId_(StudentService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateStudent_(StudentService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteStudent_(StudentService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListStudents_(StudentService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StudentService::Stub::CreateStudent(::grpc::ClientContext* context, const ::accounts::CreateStudentRequest& request, ::accounts::CreateStudentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::CreateStudentRequest, ::accounts::CreateStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateStudent_, context, request, response);
}

void StudentService::Stub::async::CreateStudent(::grpc::ClientContext* context, const ::accounts::CreateStudentRequest* request, ::accounts::CreateStudentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::CreateStudentRequest, ::accounts::CreateStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateStudent_, context, request, response, std::move(f));
}

void StudentService::Stub::async::CreateStudent(::grpc::ClientContext* context, const ::accounts::CreateStudentRequest* request, ::accounts::CreateStudentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateStudent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::CreateStudentResponse>* StudentService::Stub::PrepareAsyncCreateStudentRaw(::grpc::ClientContext* context, const ::accounts::CreateStudentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::CreateStudentResponse, ::accounts::CreateStudentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateStudent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::CreateStudentResponse>* StudentService::Stub::AsyncCreateStudentRaw(::grpc::ClientContext* context, const ::accounts::CreateStudentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateStudentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentService::Stub::GetStudent(::grpc::ClientContext* context, const ::accounts::GetStudentRequest& request, ::accounts::GetStudentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::GetStudentRequest, ::accounts::GetStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStudent_, context, request, response);
}

void StudentService::Stub::async::GetStudent(::grpc::ClientContext* context, const ::accounts::GetStudentRequest* request, ::accounts::GetStudentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::GetStudentRequest, ::accounts::GetStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudent_, context, request, response, std::move(f));
}

void StudentService::Stub::async::GetStudent(::grpc::ClientContext* context, const ::accounts::GetStudentRequest* request, ::accounts::GetStudentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetStudentResponse>* StudentService::Stub::PrepareAsyncGetStudentRaw(::grpc::ClientContext* context, const ::accounts::GetStudentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::GetStudentResponse, ::accounts::GetStudentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStudent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetStudentResponse>* StudentService::Stub::AsyncGetStudentRaw(::grpc::ClientContext* context, const ::accounts::GetStudentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStudentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentService::Stub::GetStudentByUserId(::grpc::ClientContext* context, const ::accounts::GetStudentByUserIdRequest& request, ::accounts::GetStudentByUserIdResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::GetStudentByUserIdRequest, ::accounts::GetStudentByUserIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStudentByUserId_, context, request, response);
}

void StudentService::Stub::async::GetStudentByUserId(::grpc::ClientContext* context, const ::accounts::GetStudentByUserIdRequest* request, ::accounts::GetStudentByUserIdResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::GetStudentByUserIdRequest, ::accounts::GetStudentByUserIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudentByUserId_, context, request, response, std::move(f));
}

void StudentService::Stub::async::GetStudentByUserId(::grpc::ClientContext* context, const ::accounts::GetStudentByUserIdRequest* request, ::accounts::GetStudentByUserIdResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudentByUserId_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetStudentByUserIdResponse>* StudentService::Stub::PrepareAsyncGetStudentByUserIdRaw(::grpc::ClientContext* context, const ::accounts::GetStudentByUserIdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::GetStudentByUserIdResponse, ::accounts::GetStudentByUserIdRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStudentByUserId_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetStudentByUserIdResponse>* StudentService::Stub::AsyncGetStudentByUserIdRaw(::grpc::ClientContext* context, const ::accounts::GetStudentByUserIdRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStudentByUserIdRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentService::Stub::UpdateStudent(::grpc::ClientContext* context, const ::accounts::UpdateStudentRequest& request, ::accounts::UpdateStudentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::UpdateStudentRequest, ::accounts::UpdateStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateStudent_, context, request, response);
}

void StudentService::Stub::async::UpdateStudent(::grpc::ClientContext* context, const ::accounts::UpdateStudentRequest* request, ::accounts::UpdateStudentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::UpdateStudentRequest, ::accounts::UpdateStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateStudent_, context, request, response, std::move(f));
}

void StudentService::Stub::async::UpdateStudent(::grpc::ClientContext* context, const ::accounts::UpdateStudentRequest* request, ::accounts::UpdateStudentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateStudent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::UpdateStudentResponse>* StudentService::Stub::PrepareAsyncUpdateStudentRaw(::grpc::ClientContext* context, const ::accounts::UpdateStudentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::UpdateStudentResponse, ::accounts::UpdateStudentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateStudent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::UpdateStudentResponse>* StudentService::Stub::AsyncUpdateStudentRaw(::grpc::ClientContext* context, const ::accounts::UpdateStudentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateStudentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentService::Stub::DeleteStudent(::grpc::ClientContext* context, const ::accounts::DeleteStudentRequest& request, ::accounts::DeleteStudentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::DeleteStudentRequest, ::accounts::DeleteStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteStudent_, context, request, response);
}

void StudentService::Stub::async::DeleteStudent(::grpc::ClientContext* context, const ::accounts::DeleteStudentRequest* request, ::accounts::DeleteStudentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::DeleteStudentRequest, ::accounts::DeleteStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStudent_, context, request, response, std::move(f));
}

void StudentService::Stub::async::DeleteStudent(::grpc::ClientContext* context, const ::accounts::DeleteStudentRequest* request, ::accounts::DeleteStudentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStudent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::DeleteStudentResponse>* StudentService::Stub::PrepareAsyncDeleteStudentRaw(::grpc::ClientContext* context, const ::accounts::DeleteStudentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::DeleteStudentResponse, ::accounts::DeleteStudentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteStudent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::DeleteStudentResponse>* StudentService::Stub::AsyncDeleteStudentRaw(::grpc::ClientContext* context, const ::accounts::DeleteStudentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteStudentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentService::Stub::ListStudents(::grpc::ClientContext* context, const ::accounts::ListStudentsRequest& request, ::accounts::ListStudentsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::ListStudentsRequest, ::accounts::ListStudentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListStudents_, context, request, response);
}

void StudentService::Stub::async::ListStudents(::grpc::ClientContext* context, const ::accounts::ListStudentsRequest* request, ::accounts::ListStudentsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::ListStudentsRequest, ::accounts::ListStudentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListStudents_, context, request, response, std::move(f));
}

void StudentService::Stub::async::ListStudents(::grpc::ClientContext* context, const ::accounts::ListStudentsRequest* request, ::accounts::ListStudentsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListStudents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::ListStudentsResponse>* StudentService::Stub::PrepareAsyncListStudentsRaw(::grpc::ClientContext* context, const ::accounts::ListStudentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::ListStudentsResponse, ::accounts::ListStudentsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListStudents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::ListStudentsResponse>* StudentService::Stub::AsyncListStudentsRaw(::grpc::ClientContext* context, const ::accounts::ListStudentsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListStudentsRaw(context, request, cq);
  result->StartCall();
  return result;
}

StudentService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::accounts::CreateStudentRequest, ::accounts::CreateStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::CreateStudentRequest* req,
             ::accounts::CreateStudentResponse* resp) {
               return service->CreateStudent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::accounts::GetStudentRequest, ::accounts::GetStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::GetStudentRequest* req,
             ::accounts::GetStudentResponse* resp) {
               return service->GetStudent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::accounts::GetStudentByUserIdRequest, ::accounts::GetStudentByUserIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::GetStudentByUserIdRequest* req,
             ::accounts::GetStudentByUserIdResponse* resp) {
               return service->GetStudentByUserId(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::accounts::UpdateStudentRequest, ::accounts::UpdateStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::UpdateStudentRequest* req,
             ::accounts::UpdateStudentResponse* resp) {
               return service->UpdateStudent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::accounts::DeleteStudentRequest, ::accounts::DeleteStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::DeleteStudentRequest* req,
             ::accounts::DeleteStudentResponse* resp) {
               return service->DeleteStudent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::accounts::ListStudentsRequest, ::accounts::ListStudentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::ListStudentsRequest* req,
             ::accounts::ListStudentsResponse* resp) {
               return service->ListStudents(ctx, req, resp);
             }, this)));
}

StudentService::Service::~Service() {
}

::grpc::Status StudentService::Service::CreateStudent(::grpc::ServerContext* context, const ::accounts::CreateStudentRequest* request, ::accounts::CreateStudentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentService::Service::GetStudent(::grpc::ServerContext* context, const ::accounts::GetStudentRequest* request, ::accounts::GetStudentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentService::Service::GetStudentByUserId(::grpc::ServerContext* context, const ::accounts::GetStudentByUserIdRequest* request, ::accounts::GetStudentByUserIdResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentService::Service::UpdateStudent(::grpc::ServerContext* context, const ::accounts::UpdateStudentRequest* request, ::accounts::UpdateStudentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentService::Service::DeleteStudent(::grpc::ServerContext* context, const ::accounts::DeleteStudentRequest* request, ::accounts::DeleteStudentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentService::Service::ListStudents(::grpc::ServerContext* context, const ::accounts::ListStudentsRequest* request, ::accounts::ListStudentsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* SchoolService_method_names[] = {
  "/accounts.SchoolService/CreateSchool",
  "/accounts.SchoolService/GetSchool",
  "/accounts.SchoolService/GetSchoolByName",
  "/accounts.SchoolService/UpdateSchool",
  "/accounts.SchoolService/DeleteSchool",
  "/accounts.SchoolService/ListSchools",
};

std::unique_ptr< SchoolService::Stub> SchoolService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SchoolService::Stub> stub(new SchoolService::Stub(channel, options));
  return stub;
}

SchoolService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateSchool_(SchoolService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSchool_(SchoolService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSchoolByName_(SchoolService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateSchool_(SchoolService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteSchool_(SchoolService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListSchools_(SchoolService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SchoolService::Stub::CreateSchool(::grpc::ClientContext* context, const ::accounts::CreateSchoolRequest& request, ::accounts::CreateSchoolResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::CreateSchoolRequest, ::accounts::CreateSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateSchool_, context, request, response);
}

void SchoolService::Stub::async::CreateSchool(::grpc::ClientContext* context, const ::accounts::CreateSchoolRequest* request, ::accounts::CreateSchoolResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::CreateSchoolRequest, ::accounts::CreateSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateSchool_, context, request, response, std::move(f));
}

void SchoolService::Stub::async::CreateSchool(::grpc::ClientContext* context, const ::accounts::CreateSchoolRequest* request, ::accounts::CreateSchoolResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateSchool_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::CreateSchoolResponse>* SchoolService::Stub::PrepareAsyncCreateSchoolRaw(::grpc::ClientContext* context, const ::accounts::CreateSchoolRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::CreateSchoolResponse, ::accounts::CreateSchoolRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateSchool_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::CreateSchoolResponse>* SchoolService::Stub::AsyncCreateSchoolRaw(::grpc::ClientContext* context, const ::accounts::CreateSchoolRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateSchoolRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SchoolService::Stub::GetSchool(::grpc::ClientContext* context, const ::accounts::GetSchoolRequest& request, ::accounts::GetSchoolResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::GetSchoolRequest, ::accounts::GetSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSchool_, context, request, response);
}

void SchoolService::Stub::async::GetSchool(::grpc::ClientContext* context, const ::accounts::GetSchoolRequest* request, ::accounts::GetSchoolResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::GetSchoolRequest, ::accounts::GetSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSchool_, context, request, response, std::move(f));
}

void SchoolService::Stub::async::GetSchool(::grpc::ClientContext* context, const ::accounts::GetSchoolRequest* request, ::accounts::GetSchoolResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSchool_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetSchoolResponse>* SchoolService::Stub::PrepareAsyncGetSchoolRaw(::grpc::ClientContext* context, const ::accounts::GetSchoolRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::GetSchoolResponse, ::accounts::GetSchoolRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSchool_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetSchoolResponse>* SchoolService::Stub::AsyncGetSchoolRaw(::grpc::ClientContext* context, const ::accounts::GetSchoolRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSchoolRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SchoolService::Stub::GetSchoolByName(::grpc::ClientContext* context, const ::accounts::GetSchoolByNameRequest& request, ::accounts::GetSchoolByNameResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::GetSchoolByNameRequest, ::accounts::GetSchoolByNameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSchoolByName_, context, request, response);
}

void SchoolService::Stub::async::GetSchoolByName(::grpc::ClientContext* context, const ::accounts::GetSchoolByNameRequest* request, ::accounts::GetSchoolByNameResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::GetSchoolByNameRequest, ::accounts::GetSchoolByNameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSchoolByName_, context, request, response, std::move(f));
}

void SchoolService::Stub::async::GetSchoolByName(::grpc::ClientContext* context, const ::accounts::GetSchoolByNameRequest* request, ::accounts::GetSchoolByNameResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSchoolByName_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetSchoolByNameResponse>* SchoolService::Stub::PrepareAsyncGetSchoolByNameRaw(::grpc::ClientContext* context, const ::accounts::GetSchoolByNameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::GetSchoolByNameResponse, ::accounts::GetSchoolByNameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSchoolByName_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetSchoolByNameResponse>* SchoolService::Stub::AsyncGetSchoolByNameRaw(::grpc::ClientContext* context, const ::accounts::GetSchoolByNameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSchoolByNameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SchoolService::Stub::UpdateSchool(::grpc::ClientContext* context, const ::accounts::UpdateSchoolRequest& request, ::accounts::UpdateSchoolResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::UpdateSchoolRequest, ::accounts::UpdateSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateSchool_, context, request, response);
}

void SchoolService::Stub::async::UpdateSchool(::grpc::ClientContext* context, const ::accounts::UpdateSchoolRequest* request, ::accounts::UpdateSchoolResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::UpdateSchoolRequest, ::accounts::UpdateSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSchool_, context, request, response, std::move(f));
}

void SchoolService::Stub::async::UpdateSchool(::grpc::ClientContext* context, const ::accounts::UpdateSchoolRequest* request, ::accounts::UpdateSchoolResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSchool_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::UpdateSchoolResponse>* SchoolService::Stub::PrepareAsyncUpdateSchoolRaw(::grpc::ClientContext* context, const ::accounts::UpdateSchoolRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::UpdateSchoolResponse, ::accounts::UpdateSchoolRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateSchool_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::UpdateSchoolResponse>* SchoolService::Stub::AsyncUpdateSchoolRaw(::grpc::ClientContext* context, const ::accounts::UpdateSchoolRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateSchoolRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SchoolService::Stub::DeleteSchool(::grpc::ClientContext* context, const ::accounts::DeleteSchoolRequest& request, ::accounts::DeleteSchoolResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::DeleteSchoolRequest, ::accounts::DeleteSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteSchool_, context, request, response);
}

void SchoolService::Stub::async::DeleteSchool(::grpc::ClientContext* context, const ::accounts::DeleteSchoolRequest* request, ::accounts::DeleteSchoolResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::DeleteSchoolRequest, ::accounts::DeleteSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteSchool_, context, request, response, std::move(f));
}

void SchoolService::Stub::async::DeleteSchool(::grpc::ClientContext* context, const ::accounts::DeleteSchoolRequest* request, ::accounts::DeleteSchoolResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteSchool_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::DeleteSchoolResponse>* SchoolService::Stub::PrepareAsyncDeleteSchoolRaw(::grpc::ClientContext* context, const ::accounts::DeleteSchoolRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::DeleteSchoolResponse, ::accounts::DeleteSchoolRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteSchool_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::DeleteSchoolResponse>* SchoolService::Stub::AsyncDeleteSchoolRaw(::grpc::ClientContext* context, const ::accounts::DeleteSchoolRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteSchoolRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SchoolService::Stub::ListSchools(::grpc::ClientContext* context, const ::accounts::ListSchoolsRequest& request, ::accounts::ListSchoolsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::ListSchoolsRequest, ::accounts::ListSchoolsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListSchools_, context, request, response);
}

void SchoolService::Stub::async::ListSchools(::grpc::ClientContext* context, const ::accounts::ListSchoolsRequest* request, ::accounts::ListSchoolsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::ListSchoolsRequest, ::accounts::ListSchoolsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSchools_, context, request, response, std::move(f));
}

void SchoolService::Stub::async::ListSchools(::grpc::ClientContext* context, const ::accounts::ListSchoolsRequest* request, ::accounts::ListSchoolsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSchools_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::ListSchoolsResponse>* SchoolService::Stub::PrepareAsyncListSchoolsRaw(::grpc::ClientContext* context, const ::accounts::ListSchoolsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::ListSchoolsResponse, ::accounts::ListSchoolsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListSchools_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::ListSchoolsResponse>* SchoolService::Stub::AsyncListSchoolsRaw(::grpc::ClientContext* context, const ::accounts::ListSchoolsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListSchoolsRaw(context, request, cq);
  result->StartCall();
  return result;
}

SchoolService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SchoolService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SchoolService::Service, ::accounts::CreateSchoolRequest, ::accounts::CreateSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SchoolService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::CreateSchoolRequest* req,
             ::accounts::CreateSchoolResponse* resp) {
               return service->CreateSchool(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SchoolService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SchoolService::Service, ::accounts::GetSchoolRequest, ::accounts::GetSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SchoolService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::GetSchoolRequest* req,
             ::accounts::GetSchoolResponse* resp) {
               return service->GetSchool(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SchoolService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SchoolService::Service, ::accounts::GetSchoolByNameRequest, ::accounts::GetSchoolByNameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SchoolService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::GetSchoolByNameRequest* req,
             ::accounts::GetSchoolByNameResponse* resp) {
               return service->GetSchoolByName(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SchoolService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SchoolService::Service, ::accounts::UpdateSchoolRequest, ::accounts::UpdateSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SchoolService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::UpdateSchoolRequest* req,
             ::accounts::UpdateSchoolResponse* resp) {
               return service->UpdateSchool(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SchoolService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SchoolService::Service, ::accounts::DeleteSchoolRequest, ::accounts::DeleteSchoolResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SchoolService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::DeleteSchoolRequest* req,
             ::accounts::DeleteSchoolResponse* resp) {
               return service->DeleteSchool(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SchoolService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SchoolService::Service, ::accounts::ListSchoolsRequest, ::accounts::ListSchoolsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SchoolService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::ListSchoolsRequest* req,
             ::accounts::ListSchoolsResponse* resp) {
               return service->ListSchools(ctx, req, resp);
             }, this)));
}

SchoolService::Service::~Service() {
}

::grpc::Status SchoolService::Service::CreateSchool(::grpc::ServerContext* context, const ::accounts::CreateSchoolRequest* request, ::accounts::CreateSchoolResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SchoolService::Service::GetSchool(::grpc::ServerContext* context, const ::accounts::GetSchoolRequest* request, ::accounts::GetSchoolResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SchoolService::Service::GetSchoolByName(::grpc::ServerContext* context, const ::accounts::GetSchoolByNameRequest* request, ::accounts::GetSchoolByNameResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SchoolService::Service::UpdateSchool(::grpc::ServerContext* context, const ::accounts::UpdateSchoolRequest* request, ::accounts::UpdateSchoolResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SchoolService::Service::DeleteSchool(::grpc::ServerContext* context, const ::accounts::DeleteSchoolRequest* request, ::accounts::DeleteSchoolResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SchoolService::Service::ListSchools(::grpc::ServerContext* context, const ::accounts::ListSchoolsRequest* request, ::accounts::ListSchoolsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ResearcherService_method_names[] = {
  "/accounts.ResearcherService/CreateResearcher",
  "/accounts.ResearcherService/GetResearcher",
  "/accounts.ResearcherService/GetResearcherByUserId",
  "/accounts.ResearcherService/UpdateResearcher",
  "/accounts.ResearcherService/DeleteResearcher",
  "/accounts.ResearcherService/ListResearchers",
};

std::unique_ptr< ResearcherService::Stub> ResearcherService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ResearcherService::Stub> stub(new ResearcherService::Stub(channel, options));
  return stub;
}

ResearcherService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateResearcher_(ResearcherService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetResearcher_(ResearcherService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetResearcherByUserId_(ResearcherService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateResearcher_(ResearcherService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteResearcher_(ResearcherService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListResearchers_(ResearcherService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ResearcherService::Stub::CreateResearcher(::grpc::ClientContext* context, const ::accounts::CreateResearcherRequest& request, ::accounts::CreateResearcherResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::CreateResearcherRequest, ::accounts::CreateResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateResearcher_, context, request, response);
}

void ResearcherService::Stub::async::CreateResearcher(::grpc::ClientContext* context, const ::accounts::CreateResearcherRequest* request, ::accounts::CreateResearcherResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::CreateResearcherRequest, ::accounts::CreateResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateResearcher_, context, request, response, std::move(f));
}

void ResearcherService::Stub::async::CreateResearcher(::grpc::ClientContext* context, const ::accounts::CreateResearcherRequest* request, ::accounts::CreateResearcherResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateResearcher_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::CreateResearcherResponse>* ResearcherService::Stub::PrepareAsyncCreateResearcherRaw(::grpc::ClientContext* context, const ::accounts::CreateResearcherRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::CreateResearcherResponse, ::accounts::CreateResearcherRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateResearcher_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::CreateResearcherResponse>* ResearcherService::Stub::AsyncCreateResearcherRaw(::grpc::ClientContext* context, const ::accounts::CreateResearcherRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateResearcherRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ResearcherService::Stub::GetResearcher(::grpc::ClientContext* context, const ::accounts::GetResearcherRequest& request, ::accounts::GetResearcherResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::GetResearcherRequest, ::accounts::GetResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetResearcher_, context, request, response);
}

void ResearcherService::Stub::async::GetResearcher(::grpc::ClientContext* context, const ::accounts::GetResearcherRequest* request, ::accounts::GetResearcherResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::GetResearcherRequest, ::accounts::GetResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetResearcher_, context, request, response, std::move(f));
}

void ResearcherService::Stub::async::GetResearcher(::grpc::ClientContext* context, const ::accounts::GetResearcherRequest* request, ::accounts::GetResearcherResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetResearcher_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetResearcherResponse>* ResearcherService::Stub::PrepareAsyncGetResearcherRaw(::grpc::ClientContext* context, const ::accounts::GetResearcherRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::GetResearcherResponse, ::accounts::GetResearcherRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetResearcher_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetResearcherResponse>* ResearcherService::Stub::AsyncGetResearcherRaw(::grpc::ClientContext* context, const ::accounts::GetResearcherRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetResearcherRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ResearcherService::Stub::GetResearcherByUserId(::grpc::ClientContext* context, const ::accounts::GetResearcherByUserIdRequest& request, ::accounts::GetResearcherByUserIdResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::GetResearcherByUserIdRequest, ::accounts::GetResearcherByUserIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetResearcherByUserId_, context, request, response);
}

void ResearcherService::Stub::async::GetResearcherByUserId(::grpc::ClientContext* context, const ::accounts::GetResearcherByUserIdRequest* request, ::accounts::GetResearcherByUserIdResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::GetResearcherByUserIdRequest, ::accounts::GetResearcherByUserIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetResearcherByUserId_, context, request, response, std::move(f));
}

void ResearcherService::Stub::async::GetResearcherByUserId(::grpc::ClientContext* context, const ::accounts::GetResearcherByUserIdRequest* request, ::accounts::GetResearcherByUserIdResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetResearcherByUserId_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetResearcherByUserIdResponse>* ResearcherService::Stub::PrepareAsyncGetResearcherByUserIdRaw(::grpc::ClientContext* context, const ::accounts::GetResearcherByUserIdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::GetResearcherByUserIdResponse, ::accounts::GetResearcherByUserIdRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetResearcherByUserId_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetResearcherByUserIdResponse>* ResearcherService::Stub::AsyncGetResearcherByUserIdRaw(::grpc::ClientContext* context, const ::accounts::GetResearcherByUserIdRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetResearcherByUserIdRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ResearcherService::Stub::UpdateResearcher(::grpc::ClientContext* context, const ::accounts::UpdateResearcherRequest& request, ::accounts::UpdateResearcherResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::UpdateResearcherRequest, ::accounts::UpdateResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateResearcher_, context, request, response);
}

void ResearcherService::Stub::async::UpdateResearcher(::grpc::ClientContext* context, const ::accounts::UpdateResearcherRequest* request, ::accounts::UpdateResearcherResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::UpdateResearcherRequest, ::accounts::UpdateResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateResearcher_, context, request, response, std::move(f));
}

void ResearcherService::Stub::async::UpdateResearcher(::grpc::ClientContext* context, const ::accounts::UpdateResearcherRequest* request, ::accounts::UpdateResearcherResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateResearcher_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::UpdateResearcherResponse>* ResearcherService::Stub::PrepareAsyncUpdateResearcherRaw(::grpc::ClientContext* context, const ::accounts::UpdateResearcherRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::UpdateResearcherResponse, ::accounts::UpdateResearcherRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateResearcher_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::UpdateResearcherResponse>* ResearcherService::Stub::AsyncUpdateResearcherRaw(::grpc::ClientContext* context, const ::accounts::UpdateResearcherRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateResearcherRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ResearcherService::Stub::DeleteResearcher(::grpc::ClientContext* context, const ::accounts::DeleteResearcherRequest& request, ::accounts::DeleteResearcherResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::DeleteResearcherRequest, ::accounts::DeleteResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteResearcher_, context, request, response);
}

void ResearcherService::Stub::async::DeleteResearcher(::grpc::ClientContext* context, const ::accounts::DeleteResearcherRequest* request, ::accounts::DeleteResearcherResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::DeleteResearcherRequest, ::accounts::DeleteResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteResearcher_, context, request, response, std::move(f));
}

void ResearcherService::Stub::async::DeleteResearcher(::grpc::ClientContext* context, const ::accounts::DeleteResearcherRequest* request, ::accounts::DeleteResearcherResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteResearcher_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::DeleteResearcherResponse>* ResearcherService::Stub::PrepareAsyncDeleteResearcherRaw(::grpc::ClientContext* context, const ::accounts::DeleteResearcherRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::DeleteResearcherResponse, ::accounts::DeleteResearcherRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteResearcher_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::DeleteResearcherResponse>* ResearcherService::Stub::AsyncDeleteResearcherRaw(::grpc::ClientContext* context, const ::accounts::DeleteResearcherRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteResearcherRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ResearcherService::Stub::ListResearchers(::grpc::ClientContext* context, const ::accounts::ListResearchersRequest& request, ::accounts::ListResearchersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::ListResearchersRequest, ::accounts::ListResearchersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListResearchers_, context, request, response);
}

void ResearcherService::Stub::async::ListResearchers(::grpc::ClientContext* context, const ::accounts::ListResearchersRequest* request, ::accounts::ListResearchersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::ListResearchersRequest, ::accounts::ListResearchersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListResearchers_, context, request, response, std::move(f));
}

void ResearcherService::Stub::async::ListResearchers(::grpc::ClientContext* context, const ::accounts::ListResearchersRequest* request, ::accounts::ListResearchersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListResearchers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::ListResearchersResponse>* ResearcherService::Stub::PrepareAsyncListResearchersRaw(::grpc::ClientContext* context, const ::accounts::ListResearchersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::ListResearchersResponse, ::accounts::ListResearchersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListResearchers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::ListResearchersResponse>* ResearcherService::Stub::AsyncListResearchersRaw(::grpc::ClientContext* context, const ::accounts::ListResearchersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListResearchersRaw(context, request, cq);
  result->StartCall();
  return result;
}

ResearcherService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResearcherService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResearcherService::Service, ::accounts::CreateResearcherRequest, ::accounts::CreateResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ResearcherService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::CreateResearcherRequest* req,
             ::accounts::CreateResearcherResponse* resp) {
               return service->CreateResearcher(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResearcherService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResearcherService::Service, ::accounts::GetResearcherRequest, ::accounts::GetResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ResearcherService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::GetResearcherRequest* req,
             ::accounts::GetResearcherResponse* resp) {
               return service->GetResearcher(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResearcherService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResearcherService::Service, ::accounts::GetResearcherByUserIdRequest, ::accounts::GetResearcherByUserIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ResearcherService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::GetResearcherByUserIdRequest* req,
             ::accounts::GetResearcherByUserIdResponse* resp) {
               return service->GetResearcherByUserId(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResearcherService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResearcherService::Service, ::accounts::UpdateResearcherRequest, ::accounts::UpdateResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ResearcherService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::UpdateResearcherRequest* req,
             ::accounts::UpdateResearcherResponse* resp) {
               return service->UpdateResearcher(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResearcherService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResearcherService::Service, ::accounts::DeleteResearcherRequest, ::accounts::DeleteResearcherResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ResearcherService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::DeleteResearcherRequest* req,
             ::accounts::DeleteResearcherResponse* resp) {
               return service->DeleteResearcher(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResearcherService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResearcherService::Service, ::accounts::ListResearchersRequest, ::accounts::ListResearchersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ResearcherService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::ListResearchersRequest* req,
             ::accounts::ListResearchersResponse* resp) {
               return service->ListResearchers(ctx, req, resp);
             }, this)));
}

ResearcherService::Service::~Service() {
}

::grpc::Status ResearcherService::Service::CreateResearcher(::grpc::ServerContext* context, const ::accounts::CreateResearcherRequest* request, ::accounts::CreateResearcherResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ResearcherService::Service::GetResearcher(::grpc::ServerContext* context, const ::accounts::GetResearcherRequest* request, ::accounts::GetResearcherResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ResearcherService::Service::GetResearcherByUserId(::grpc::ServerContext* context, const ::accounts::GetResearcherByUserIdRequest* request, ::accounts::GetResearcherByUserIdResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ResearcherService::Service::UpdateResearcher(::grpc::ServerContext* context, const ::accounts::UpdateResearcherRequest* request, ::accounts::UpdateResearcherResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ResearcherService::Service::DeleteResearcher(::grpc::ServerContext* context, const ::accounts::DeleteResearcherRequest* request, ::accounts::DeleteResearcherResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ResearcherService::Service::ListResearchers(::grpc::ServerContext* context, const ::accounts::ListResearchersRequest* request, ::accounts::ListResearchersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* StudentProfileService_method_names[] = {
  "/accounts.StudentProfileService/CreateStudentProfile",
  "/accounts.StudentProfileService/GetStudentProfile",
  "/accounts.StudentProfileService/UpdateStudentProfile",
  "/accounts.StudentProfileService/DeleteStudentProfile",
};

std::unique_ptr< StudentProfileService::Stub> StudentProfileService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StudentProfileService::Stub> stub(new StudentProfileService::Stub(channel, options));
  return stub;
}

StudentProfileService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateStudentProfile_(StudentProfileService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStudentProfile_(StudentProfileService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateStudentProfile_(StudentProfileService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteStudentProfile_(StudentProfileService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StudentProfileService::Stub::CreateStudentProfile(::grpc::ClientContext* context, const ::accounts::CreateStudentProfileRequest& request, ::accounts::CreateStudentProfileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::CreateStudentProfileRequest, ::accounts::CreateStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateStudentProfile_, context, request, response);
}

void StudentProfileService::Stub::async::CreateStudentProfile(::grpc::ClientContext* context, const ::accounts::CreateStudentProfileRequest* request, ::accounts::CreateStudentProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::CreateStudentProfileRequest, ::accounts::CreateStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateStudentProfile_, context, request, response, std::move(f));
}

void StudentProfileService::Stub::async::CreateStudentProfile(::grpc::ClientContext* context, const ::accounts::CreateStudentProfileRequest* request, ::accounts::CreateStudentProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateStudentProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::CreateStudentProfileResponse>* StudentProfileService::Stub::PrepareAsyncCreateStudentProfileRaw(::grpc::ClientContext* context, const ::accounts::CreateStudentProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::CreateStudentProfileResponse, ::accounts::CreateStudentProfileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateStudentProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::CreateStudentProfileResponse>* StudentProfileService::Stub::AsyncCreateStudentProfileRaw(::grpc::ClientContext* context, const ::accounts::CreateStudentProfileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateStudentProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentProfileService::Stub::GetStudentProfile(::grpc::ClientContext* context, const ::accounts::GetStudentProfileRequest& request, ::accounts::GetStudentProfileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::GetStudentProfileRequest, ::accounts::GetStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStudentProfile_, context, request, response);
}

void StudentProfileService::Stub::async::GetStudentProfile(::grpc::ClientContext* context, const ::accounts::GetStudentProfileRequest* request, ::accounts::GetStudentProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::GetStudentProfileRequest, ::accounts::GetStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudentProfile_, context, request, response, std::move(f));
}

void StudentProfileService::Stub::async::GetStudentProfile(::grpc::ClientContext* context, const ::accounts::GetStudentProfileRequest* request, ::accounts::GetStudentProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudentProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetStudentProfileResponse>* StudentProfileService::Stub::PrepareAsyncGetStudentProfileRaw(::grpc::ClientContext* context, const ::accounts::GetStudentProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::GetStudentProfileResponse, ::accounts::GetStudentProfileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStudentProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::GetStudentProfileResponse>* StudentProfileService::Stub::AsyncGetStudentProfileRaw(::grpc::ClientContext* context, const ::accounts::GetStudentProfileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStudentProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentProfileService::Stub::UpdateStudentProfile(::grpc::ClientContext* context, const ::accounts::UpdateStudentProfileRequest& request, ::accounts::UpdateStudentProfileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::UpdateStudentProfileRequest, ::accounts::UpdateStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateStudentProfile_, context, request, response);
}

void StudentProfileService::Stub::async::UpdateStudentProfile(::grpc::ClientContext* context, const ::accounts::UpdateStudentProfileRequest* request, ::accounts::UpdateStudentProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::UpdateStudentProfileRequest, ::accounts::UpdateStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateStudentProfile_, context, request, response, std::move(f));
}

void StudentProfileService::Stub::async::UpdateStudentProfile(::grpc::ClientContext* context, const ::accounts::UpdateStudentProfileRequest* request, ::accounts::UpdateStudentProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateStudentProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::UpdateStudentProfileResponse>* StudentProfileService::Stub::PrepareAsyncUpdateStudentProfileRaw(::grpc::ClientContext* context, const ::accounts::UpdateStudentProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::UpdateStudentProfileResponse, ::accounts::UpdateStudentProfileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateStudentProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::UpdateStudentProfileResponse>* StudentProfileService::Stub::AsyncUpdateStudentProfileRaw(::grpc::ClientContext* context, const ::accounts::UpdateStudentProfileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateStudentProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentProfileService::Stub::DeleteStudentProfile(::grpc::ClientContext* context, const ::accounts::DeleteStudentProfileRequest& request, ::accounts::DeleteStudentProfileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::accounts::DeleteStudentProfileRequest, ::accounts::DeleteStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteStudentProfile_, context, request, response);
}

void StudentProfileService::Stub::async::DeleteStudentProfile(::grpc::ClientContext* context, const ::accounts::DeleteStudentProfileRequest* request, ::accounts::DeleteStudentProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::accounts::DeleteStudentProfileRequest, ::accounts::DeleteStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStudentProfile_, context, request, response, std::move(f));
}

void StudentProfileService::Stub::async::DeleteStudentProfile(::grpc::ClientContext* context, const ::accounts::DeleteStudentProfileRequest* request, ::accounts::DeleteStudentProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStudentProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::accounts::DeleteStudentProfileResponse>* StudentProfileService::Stub::PrepareAsyncDeleteStudentProfileRaw(::grpc::ClientContext* context, const ::accounts::DeleteStudentProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::accounts::DeleteStudentProfileResponse, ::accounts::DeleteStudentProfileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteStudentProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::accounts::DeleteStudentProfileResponse>* StudentProfileService::Stub::AsyncDeleteStudentProfileRaw(::grpc::ClientContext* context, const ::accounts::DeleteStudentProfileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteStudentProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

StudentProfileService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentProfileService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentProfileService::Service, ::accounts::CreateStudentProfileRequest, ::accounts::CreateStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentProfileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::CreateStudentProfileRequest* req,
             ::accounts::CreateStudentProfileResponse* resp) {
               return service->CreateStudentProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentProfileService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentProfileService::Service, ::accounts::GetStudentProfileRequest, ::accounts::GetStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentProfileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::GetStudentProfileRequest* req,
             ::accounts::GetStudentProfileResponse* resp) {
               return service->GetStudentProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentProfileService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentProfileService::Service, ::accounts::UpdateStudentProfileRequest, ::accounts::UpdateStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentProfileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::UpdateStudentProfileRequest* req,
             ::accounts::UpdateStudentProfileResponse* resp) {
               return service->UpdateStudentProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentProfileService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentProfileService::Service, ::accounts::DeleteStudentProfileRequest, ::accounts::DeleteStudentProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentProfileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::accounts::DeleteStudentProfileRequest* req,
             ::accounts::DeleteStudentProfileResponse* resp) {
               return service->DeleteStudentProfile(ctx, req, resp);
             }, this)));
}

StudentProfileService::Service::~Service() {
}

::grpc::Status StudentProfileService::Service::CreateStudentProfile(::grpc::ServerContext* context, const ::accounts::CreateStudentProfileRequest* request, ::accounts::CreateStudentProfileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentProfileService::Service::GetStudentProfile(::grpc::ServerContext* context, const ::accounts::GetStudentProfileRequest* request, ::accounts::GetStudentProfileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentProfileService::Service::UpdateStudentProfile(::grpc::ServerContext* context, const ::accounts::UpdateStudentProfileRequest* request, ::accounts::UpdateStudentProfileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentProfileService::Service::DeleteStudentProfile(::grpc::ServerContext* context, const ::accounts::DeleteStudentProfileRequest* request, ::accounts::DeleteStudentProfileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace accounts

