version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: group-project-auth-db
    environment:
      POSTGRES_USER: frix
      POSTGRES_PASSWORD: 07vk640xz
      POSTGRES_DB: hehe
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/home/medfrix/dev/db_volumes/group-project-auth
  
  minio:
    image: minio/minio:latest
    container_name: group-project-object-storage
    environment:
      MINIO_ROOT_USER: frix
      MINIO_ROOT_PASSWORD: 07vk640xz
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:

